version: "3"
services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "8000:80"
        volumes:
            - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    node-app:
        build: .
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - PORT=8000
        # if u using dotenv file
        # env_file:
        #   - ./.env
        depends_on:
            - mongo

    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=youruname
            - MONGO_INITDB_ROOT_PASSWORD=ursecret
        volumes:
            - mongo-db:/data/dbase

    redis:
        image: redis

volumes:
    mongo-db:
